### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by NuttyJelly** [NuttyJelly/Always-Half-Full-theme#16]

**Comment by ScheiBig** [comment]
Support of Java via semi-official Red Hat (bundled in Microsoft extension pack) could be al ot better: both syntax and semantic tokenization of language is very poor in many places, for example in following snippet:
```java
class Program {
    private App app = new App();
}
```
Neither `app` is recognized as class field, nor `App()` as constructor call, regardless of whether semantic coloring is enabled, or not.

**Comment by ScheiBig** [comment]
Tested and fixed token bugs, that are fixable (not a lot).
Current list of unfixable bugs:
- annotation `@` is styled as annotation, but annotation name is styled as interface (regardless of parenthesis),
- record definition is styled as record/struct, but its usage is styled as normal class,
- enum members are styled as normal fields, rather than enum fields,
- `super` keyword is treated as variable (even if used as callable constructor),
- constructor calls / definitions are styled like normal methods (not even as static ones),
- field declarations are styled as local variable declarations,
- no token style modifiers exists for constants

**Comment by ScheiBig** [comment]
Beside `super` keyword, all other issues are resolved, if Java project is properly opened and loaded by language server.
