### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by NuttyJelly** [NuttyJelly/Always-Half-Full-theme#2]

**Comment by ScheiBig** [comment]
All recognized token are styled. Same token limitations apply from #1, which is strange, since on declaration, struct names are semantically tokenized properly; in actual usage all enums, classes, structs and typedefs are treated as `type` token. Moreover there is problem with template parameters: typename parameters are tokenized as types, but normal parameters are treated like normal local variables (not even as const/constexpr ones).

**Comment by ScheiBig** [comment]
Also there is lack of semantic tokenization for any constants.
