### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by NuttyJelly** [NuttyJelly/Always-Half-Full-theme#3]

**Comment by ScheiBig** [comment]
One unfortunate bug that was found, decorators with arguments:
```js
@Decorator(1, "2")
class App {}
```
are treated as function calls (`@` symbol is still treated as decorator), while ones without parenthesis are tokenized as expected.

**Comment by ScheiBig** [comment]
Most likely everything is styled. Decided to change `async` modifier of functions/methods, to use italics (previously unused), rather than foreign syntax color (for better readability). Os mentioned previously one bug is present:
- decorators with parenthesis are treated as normal function calls (`@` symbol is still styled properly).
