### ISSUE TITLE
SAS

### ISSUE THREAD

**Issue by NuttyJelly** [NuttyJelly/Always-Half-Full-theme#32]

**Comment by ScheiBig** [comment]
Added full support for SAS-specific semantic tokens (or left to be inherited from parent tokens). Coloring scheme diverges slightly from general coloring scheme, since SAS is DSL that has slightly different kind of tokens from traditional programming languages.

**Comment by ScheiBig** [comment]
Color choices for SAS are:
- basic keyword persist their style,
- keywords that delimit program steps (`data`, `proc`, `run`, `quit`, etc.) are styled as foreign keywords, to differentiate them from normal keywords (just like SAS does in theirs editors),
- procedure names are styled as functions (implied by them being complex subroutines),
- `datalines` card-data is styled as fields (semi-arbitrary decision, based on them representing inline state of program),
- numerical and string literals persist their styling,
- data and/or time literals are styled as escape sequences (they are not inherently different data type in SAS, but they have different representation; since SAS does not have normal escape sequences, this style was free),
- (in)formats are styled as types (SAS actually has only 2 data types that are never named in code, but formats are much more diversified, that's why they take over this style),
- bitmasks are styled as units (implied by them being used to manipulate parts of data),
- keywords that delimit macro declarations (`%macro`, `%mend`, etc.) are styled as preprocessor functionality, since they delimit compilation steps),
- macro calls persist style of macro calls,
- macro keywords are styled as labels (this is purely arbitrary decision, this assigns only major color that is not used anywhere else).

Also should be noted, that name literals are stripped of coloring to appear just like rest of names - since that is really what they are, but are italicized to make them stand out as a whole. Same goes for macro comments - block comments and comment statements are not processed by interpreter, but are still printed in log, and being read by said interpreter; since macro-comments are not pasted into code and not read, they also are italicized.

**Comment by ScheiBig** [comment]
Changing name literal decoration from italics to underline
