### ISSUE TITLE
React (.jsx / .tsx)

### ISSUE THREAD

**Issue by NuttyJelly** [NuttyJelly/Always-Half-Full-theme#5]

**Comment by ScheiBig** [comment]
Special features of JSX are colorized in a way that makes them stand out when necessary (element tags), and blend with rest of general coding scheme otherwise (like attributes being colored like parameters, since that is how they are provided in code).

 One controversial choice is that components usage is using type colors, since traditionally components were provided as classes (and that's how Web Components work too), but attributes use parameter color (traditionally they were provided as class fields); latter could be explained using Web Components as JS DOM, where element properties are actual class fields, while attributes are more like metadata being passed for DOM renderer (like how arguments are being passed to function parameters).
